name: "Build"

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install node packages
        run: npm ci

      - name: Build all
        run: npm run esbuild-all

      - name: Run npm test
        run: npm test
      
      - name: Run ESlint
        run: |
          eslint client/src/extension.ts
          eslint client/src/test/*.ts
          eslint serer/src/*.ts
