name: "Build"

on:
  pull_request:
  push:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Restore pip cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}-${{ hashFiles('**/requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Checkout
        uses: actions/checkout@v3

      - name: ShellCheck
        uses: ludeeus/action-shellcheck@master

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Prettier
        uses: creyD/prettier_action@v4.3
        with:
          dry: true
          prettier_options: --check .
          prettier_version: 2.8.8
          clean_node_folder: false

      - name: ESlint
        run: |
          pwd
          ls -la
          ls -la ./node_modules/
          ls -la ./node_modules/.bin
          ls -la ./node_modules/.bin/eslint
          pnpm eslint

      - name: Pylint
        run: |
          pip install -r scripts/requirements.txt
          pip install -r scripts/requirements-dev.txt
          pylint scripts

      - name: Package nightly build
        if: "!startsWith(github.ref, 'refs/tags/')"
        run: |
          pnpm i --global @vscode/vsce
          vsce package

      - name: Upload nightly build
        uses: actions/upload-artifact@v3
        if: "!startsWith(github.ref, 'refs/tags/')"
        with:
          name: bgforge-mls
          path: "*.vsix"

      - name: Publish to Open VSX Registry
        if: "startsWith(github.ref, 'refs/tags/')"
        uses: HaaLeo/publish-vscode-extension@v1
        id: publishToOpenVSX
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }}

      - name: Publish to Visual Studio Marketplace
        if: "startsWith(github.ref, 'refs/tags/')"
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
          extensionFile: ${{ steps.publishToOpenVSX.outputs.vsixPath }}

      - name: GitHub Release
        if: "startsWith(github.ref, 'refs/tags/')"
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.ref_name }}
          fail_on_unmatched_files: true
          files: ${{ steps.publishToOpenVSX.outputs.vsixPath }}
