name: "Build"

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}-${{ hashFiles('**/requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - uses: actions/checkout@v3

      - name: ShellCheck
        uses: ludeeus/action-shellcheck@master

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install node packages
        run: |
          ls
          npm ci
          ls

      - name: ESlint
        run: npm run eslint

      - name: Pylint
        run: |
          pip install -r scripts/requirements.txt
          pip install -r scripts/requirements-dev.txt
          pylint scripts

      - name: Prettier
        uses: creyD/prettier_action@v4.2
        with:
          dry: true
          prettier_options: --check .

      - name: Package nightly build
        if: "!startsWith(github.ref, 'refs/tags/')"
        run: |
          pwd
          ls -la
          npm i --global @vscode/vsce
          echo $PATH
          env | grep -i node
          env | grep -i npm
          ls node_modules
          vsce package

      - name: Upload nightly build
        uses: actions/upload-artifact@v3
        if: "!startsWith(github.ref, 'refs/tags/')"
        with:
          name: bgforge-mls
          path: "*.vsix"
